[www]
user = 1000
group = 1000
listen = 9000
listen.owner = nginx
listen.group = nginx
pm = dynamic
pm.max_children = 16
pm.start_servers = 4
pm.min_spare_servers = 2
pm.max_spare_servers = 8
pm.max_requests = 1024

clear_env = no
catch_workers_output = yes
decorate_workers_output = no

php_admin_value[memory_limit] = 256M
php_value[post_max_size] = 100M
php_value[upload_max_filesize] = 100M
